# Generated by Django 5.1.4 on 2025-07-18 14:43

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_fix_transaction_id_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default=payments.models.generate_transaction_id, max_length=100, unique=True),
        ),
    ]
