# Generated by Django 5.2.4 on 2025-07-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Latest tracked price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='last_price_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='onset_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price when alert was created', max_digits=10, null=True),
        ),
    ]
