# Generated by Django 5.2.4 on 2025-07-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_pricealert_current_price_and_more'),
    ]

    operations = [
    ]
