# Generated by Django 5.2.4 on 2025-07-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20250713_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapetarget',
            name='site_type',
            field=models.CharField(choices=[('amazon_uk', 'Amazon UK'), ('currys', 'Currys PC World'), ('john_lewis', 'John Lewis & Partners'), ('argos', 'Argos'), ('tesco', 'Tesco'), ('asda', 'ASDA'), ('sainsburys', "Sainsbury's"), ('marks_spencer', 'Marks & Spencer'), ('next', 'Next'), ('house_of_fraser', 'House of Fraser'), ('selfridges', 'Selfridges'), ('harrods', 'Harrods'), ('boots', 'Boots'), ('superdrug', 'Superdrug'), ('waterstones', 'Waterstones'), ('hmv', 'HMV'), ('game', 'GAME'), ('jd_sports', 'JD Sports'), ('size', 'Size?'), ('footlocker_uk', 'Foot Locker UK'), ('asos', 'ASOS'), ('zara_uk', 'Zara UK'), ('h_and_m_uk', 'H&M UK'), ('uniqlo_uk', 'Uniqlo UK'), ('primark', 'Primark'), ('tk_maxx', 'TK Maxx'), ('b_and_q', 'B&Q'), ('homebase', 'Homebase'), ('ikea_uk', 'IKEA UK'), ('dunelm', 'Dunelm'), ('the_range', 'The Range'), ('wickes', 'Wickes'), ('screwfix', 'Screwfix'), ('toolstation', 'Toolstation'), ('very', 'Very.co.uk'), ('ao', 'AO.com'), ('custom', 'Custom Website')], max_length=50),
        ),
    ]
