# Generated by Django 4.2.23 on 2025-07-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_alter_scrapetarget_site_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='product_url',
            field=models.URLField(blank=True, help_text='External product URL to track (Amazon, eBay, etc.)', max_length=500),
        ),
    ]
