# Generated by Django 5.1.4 on 2025-07-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_pricealert_product_url'),
    ]

    operations = [
    ]
