# Generated by Django 5.2.4 on 2025-07-04 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_categor_50f5f1_idx',
            old_name='products_pr_categor_a5b5d6_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_is_feat_a1ecf6_idx',
            old_name='products_pr_is_feat_e4e9b3_idx',
        ),
    ]
