# Generated by Django 5.2.4 on 2025-07-13 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_products_pr_categor_a5b5d6_idx_products_pr_categor_50f5f1_idx_and_more'),
    ]

    operations = [
    ]
