# Generated by Django 5.2.4 on 2025-07-16 02:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='products/default', max_length=255, null=True, verbose_name='image'),
        ),
    ]
